[08/09/2025 21:53:00] üìåGera√ß√£o do TXT iniciada (09/2025 ‚Üí 09/2025)‚Ä¶
[08/09/2025 21:53:00] üìåIniciando leitura da planilha‚Ä¶
[08/09/2025 21:53:00] ‚ÑπÔ∏èLeitura 09/2025: 3 funcion√°rios ‚Äì INSS=420000 IRRF=84000 FGTS=21000
[08/09/2025 21:53:00] ‚ùåErro inesperado: Traceback (most recent call last): File "c:\Users\Victor\Desktop\CODIGOS\Trabalho\LIVRO CAIXA\SISTEMA-LCDPR\Importa√ß√£o Folha\automacao_folha.py", line 632, in run if self._exists_in_db(data_trib_br, imovel_use, cnpj, str(cents), historico): ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "c:\Users\Victor\Desktop\CODIGOS\Trabalho\LIVRO CAIXA\SISTEMA-LCDPR\Importa√ß√£o Folha\automacao_folha.py", line 533, in _exists_in_db id_im = self._imovel_id(cod_imovel) File "c:\Users\Victor\Desktop\CODIGOS\Trabalho\LIVRO CAIXA\SISTEMA-LCDPR\Importa√ß√£o Folha\automacao_folha.py", line 514, in _imovel_id row = db.fetch_one("SELECT id FROM imovel_rural WHERE cod_imovel=?", (alt,)) File "c:\Users\Victor\Desktop\CODIGOS\Trabalho\LIVRO CAIXA\SISTEMA-LCDPR\sistema.py", line 478, in fetch_one return self.execute_query(sql, params).fetchone() ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^ File "c:\Users\Victor\Desktop\CODIGOS\Trabalho\LIVRO CAIXA\SISTEMA-LCDPR\sistema.py", line 437, in execute_query cur = self.conn.cursor() sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 2136 and this is thread id 25388. 